services:
  db:
    image: postgres:16
    environment:
      PGTZ: America/Sao_Paulo
      POSTGRES_USER: azn
      POSTGRES_PASSWORD: azn
      POSTGRES_DB: azn
    ports:
      - "5432:5432"
    volumes:
      - azn_pg:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgres://azn:azn@db:5432/azn
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  azn_pg:
